* DesOwen
** uses

This medication is used to treat a variety of skin conditions (e.g., eczema, dermatitis, allergies, rash). Desonide reduces the swelling, itching and redness that can occur in these types of conditions. Desonide is a mild corticosteroid.
How to use DesOwen topical

Use this medication only on the skin.

Shake the bottle well before using. Wash your hands. Clean and dry the affected area. Apply a thin film of medication to the affected area and gently rub in, usually 2-3 times daily, or as directed by your doctor. Do not bandage, wrap, or cover the area unless you are instructed to do so by your doctor. If used in the diaper area on an infant, do not use tight-fitting diapers or plastic pants
** side effect

Burning, stinging, itching, irritation, dryness, or redness may occur when first applied to the skin. This should disappear in a few days as your body adjusts to the medication. If any of these effects persist or worsen, notify your doctor or pharmacist promptly.
* Ventolin
** Uses

Albuterol (also known as salbutamol) is used to treat wheezing and shortness of breath caused by breathing problems (such as asthma, chronic obstructive pulmonary disease). Albuterol belongs to a class of drugs known as bronchodilators. It works in the airways by opening breathing passages and relaxing muscles. Controlling symptoms of breathing problems can decrease time lost from work or school.

This medication is taken by mouth and does not work right away. It should not be used for sudden attacks of breathing trouble. Your doctor may prescribe a quick-relief inhaler for sudden shortness of breath/asthma attacks while you are on this medication. Always have the quick-relief inhaler with you. Consult your doctor or pharmacist for more details.
How to use Ventolin

Take this medication by mouth as directed by your doctor, usually 3 or 4 times daily. Dosage is based on your medical condition and response to treatment. Adults and children older than 12 years should not take more than 32 milligrams a day. Children aged 6 to 12 years should not take more than 24 milligrams a day.

Use this medication regularly to get the most benefit from it. To help you remember, take it at the same times each day. Do not increase your dose or take it more frequently than prescribed.

Learn which of your medications you should use every day and which you should use if your breathing suddenly worsens. Ask your doctor what to do if you have worsening cough or shortness of breath, wheezing, increased sputum, worsening peak flow meter readings, increased use of your quick-relief inhaler, or if your quick-relief inhaler does not seem to be working well. Learn when you can self-medicate and when you should get medical help right away.
** side effect
Nervousness, shaking (tremor), headache, or dizziness may occur. If any of these effects persist or worsen, tell your doctor or pharmacist promptly.
* Elixir
** Uses
This combination medication is used to temporarily relieve symptoms caused by the common cold, flu, allergies, or other breathing illnesses (such as sinusitis, bronchitis). Antihistamines help relieve watery eyes, itchy eyes/nose/throat, runny nose, and sneezing. Decongestants help to relieve stuffy nose and ear congestion symptoms.
** side effect
Drowsiness, dizziness, dry mouth/nose/throat, headache, upset stomach, constipation, or trouble sleeping may occur. If any of these effects persist or worsen, tell your doctor or pharmacist promptly.
* Zyrtec
** Uses
Cetirizine is an antihistamine used to relieve allergy symptoms such as watery eyes, runny nose, itching eyes/nose, sneezing, hives, and itching. It works by blocking a certain natural substance (histamine) that your body makes during an allergic reaction.

Cetirizine does not prevent hives or prevent/treat a serious allergic reaction (such as anaphylaxis). Therefore, if your doctor has prescribed epinephrine to treat allergic reactions, always carry your epinephrine injector with you. Do not use cetirizine in place of your epinephrine.
** Side effect
Drowsiness, tiredness, and dry mouth may occur. Stomach pain may also occur, especially in children. If any of these effects persist or worsen, tell your doctor or pharmacist promptly.
* Reference
http://www.webmd.com/drugs/2/drug-12127/zyrtec-oral/details#side-effects
